///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RecordingSearch recording.
    /// </summary>
    [TestModule("e5418f1b-de4a-4d34-a8a7-f3c40b6ef29e", ModuleType.Recording, 1)]
    public partial class RecordingSearch : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1Repository repository.
        /// </summary>
        public static MyTest1Repository repo = MyTest1Repository.Instance;

        static RecordingSearch instance = new RecordingSearch();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RecordingSearch()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RecordingSearch Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Placeholder='Search') on item 'ApplicationUnderTest.SearchQueryTop'.", repo.ApplicationUnderTest.SearchQueryTopInfo, new RecordItemIndex(0));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SearchQueryTopInfo, "Placeholder", "Search");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='') on item 'ApplicationUnderTest.SearchQueryTop'.", repo.ApplicationUnderTest.SearchQueryTopInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SearchQueryTopInfo, "Value", "");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SearchQueryTop' at 106;19.", repo.ApplicationUnderTest.SearchQueryTopInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.SearchQueryTop.Click("106;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'abc' with focus on 'ApplicationUnderTest.SearchQueryTop'.", repo.ApplicationUnderTest.SearchQueryTopInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.SearchQueryTop.PressKeys("abc");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='abc') on item 'ApplicationUnderTest.SearchQueryTop'.", repo.ApplicationUnderTest.SearchQueryTopInfo, new RecordItemIndex(4));
            Validate.AttributeEqual(repo.ApplicationUnderTest.SearchQueryTopInfo, "Value", "abc");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SearchQueryTop' at 219;15.", repo.ApplicationUnderTest.SearchQueryTopInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.SearchQueryTop.Click("219;15");
            Delay.Milliseconds(0);
            
            validateSearchSuggestions(repo.ApplicationUnderTest.SearchPage.SearchSuggestionInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
