///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest1
{
    public partial class Recording2
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

//        public static void SelectOption(this SelectTag selectBox, string itemName)  
//		{  
//		    Report.Info("Selecting item '"+itemName+"' in "+selectBox);  
//		      
//		    // ignore case regex  
//		    string itemRegex = "^(?i)" + Regex.Escape(itemName) + "$";  
//		  
//		    selectBox.EnsureVisible();  
//		              
//		    OptionTag option = selectBox.FindSingle<OptionTag>("option[@InnerText~'"+itemRegex+"']");  
//		    option.Selected = true;  
//		}

        public void Mouse_Click_ContactUsMyStoreGoogleChrome(RepoItemInfo formInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'formInfo' at 587;672.", formInfo);
            formInfo.FindAdapter<Form>().Click("587;672");
        }

        public void Mouse_Click_LoginMyStoreGoogleChrome(RepoItemInfo formInfo)
        {
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'formInfo' at 520;733.", formInfo);
            formInfo.FindAdapter<Form>().Click("520;733");
        }  
    }
}
